import http from "node:http"; import WebSocket from "ws";
const get=p=>new Promise((res,rej)=>{http.get("http://127.0.0.1:9333"+p,r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>res(JSON.parse(d)))}).on("error",rej)});
const ver=await get("/json/version"); const ws=new WebSocket(ver.webSocketDebuggerUrl,{perMessageDeflate:false});
let id=0;const p=new Map();const send=(m,pa={},s)=>new Promise(r=>{const i=++id;p.set(i,r);ws.send(JSON.stringify({id:i,method:m,params:pa,sessionId:s}))});
await new Promise(r=>ws.on("open",r));ws.on("message",raw=>{const m=JSON.parse(raw);if(m.id&&p.has(m.id)){p.get(m.id)(m.result);p.delete(m.id)}});
const {targetId}=await send("Target.createTarget",{url:"about:blank"});const {sessionId}=await send("Target.attachToTarget",{targetId,flatten:true});
await send("Page.enable",{},sessionId);await send("Page.navigate",{url:"http://127.0.0.1:4521/#/tools"},sessionId);
await new Promise(r=>setTimeout(r,2000));
const r=await send("Runtime.evaluate",{expression:`Array.from(document.querySelector('#app').children).map(e=>e.tagName+(e.id?'#'+e.id:'')+'.'+(e.className||'').split(' ')[0])`,returnByValue:true},sessionId);
console.log(JSON.stringify(r.result.value,null,2));
await send("Target.closeTarget",{targetId});ws.close();
